name: Novena Cron
on:
  push:
    branches: [feature/novena-discord]
  schedule:
    - cron: '30 2 * * *'  # 2:30 AM UTC
    - cron: '0 6 * * *'   # 6 AM UTC
    - cron: '0 9 * * *'   # 9 AM UTC
    - cron: '0 12 * * *'  # 12 PM UTC
    - cron: '0 15 * * *'  # 3 PM UTC
    - cron: '0 18 * * *'  # 6 PM UTC
    - cron: '0 21 * * *'  # 9 PM UTC
jobs:
  trigger-cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call Vercel Cron Endpoint
        run: curl -X GET "https://stag-quest.vercel.app/api/cron"