name: Novena Cron
on:
  schedule:
    - cron: '30 2 * * *'  # 2:30 AM UTC (Matins)
    - cron: '0 6 * * *'   # 6 AM UTC (Lauds)
    - cron: '0 9 * * *'   # 9 AM UTC (Terce)
    - cron: '0 12 * * *'  # 12 PM UTC (Sext)
    - cron: '0 15 * * *'  # 3 PM UTC (None)
    - cron: '0 18 * * *'  # 6 PM UTC (Vespers)
    - cron: '0 21 * * *'  # 9 PM UTC (Compline)
jobs:
  trigger-cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call Vercel Cron Endpoint
        run: curl -X GET "https://stag-quest.vercel.app/api/cron"